### ISSUE TITLE
How to merge?

### ISSUE THREAD

**Issue by Stan92** [chikien276/MultipartHelper#1]
Hi,
Do you have any example using your component?
I don't know how to merge the chunked files stored into the temp folder
Thx

**Comment by chikien276** [comment]
I don't really understand your question and what are you trying to do. Are you trying to split a file into chunks in client-side then upload those chunks one by one? Or, you are trying to upload a single file (big or small) using `multipart/form-data`? If the first question's answer is yes it will be a long example, if the second's answer is, you can do something like
```
[HttpPost("/Upload/Index/{id:int}")]
        [DisableFormValueModelBinding]
        public async Task<IActionResult> Index1(int Id)
        {
            if (!MultipartRequestHelper.IsMultipartContentType(Request.ContentType))
            {
                return BadRequest("Expected a multipart request, but got " +
                    Request.ContentType);
            }
            Directory.CreateDirectory("/temporary/folder");
            (Object model, List<LocalMultipartFileInfo>files) = await FileUploadHelper
                    .ParseRequestForm(this, "/Your/Temporary/Folder", 
                        new Object()); // asumming you don't care about model here

            // By now you have your files uploaded on /Your/Temporary/Folder
            // just copy those to wherever you want or do whatever you want with fully uploaded file
            // fully path to these files are in LocalMultipartFileInfo.TemporaryLocation
            return Ok();
        }
```

**Comment by Stan92** [comment]
I thank you for your reply.. 
In fact, I use dropzone.js plugin and I use the method that allows to split the file in chunks.

**Comment by Stan92** [comment]
Ok I got it..
I removed the chunk configuration and use the solution you gave.
I had to add a web.config file (I use IIS) and set a value for the security/requestFiltering/requestLimits/ maxAllowedContentLength attribute..
Seems to work..
Thx..

**Comment by Stan92** [comment]
I got it..
I removed the chunk management (dropzone.js), used your solution.
I have to add a web.config file (I use IIS) and set a value to the attribute : 
system.webServer/security/requestFiltering/requestLimits/maxAllowedContentLength 

It seems to work.. 
Thanks
